// <auto-generated />
using System;
using ComponentLibTests.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComponentLibTests.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917114049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.EntityInternEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EntityInternRiskLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDateMatcher")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("Entity");

                    b.HasIndex("EntityInternRiskLevelId");

                    b.ToTable("EntityInternEntities");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.EntityInternRiskLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Sort")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("EntityInternRiskLevels");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.EntityMatchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityInternEntitiesId")
                        .HasColumnType("int");

                    b.Property<int>("EntityMatchStatusId")
                        .HasColumnType("int");

                    b.Property<double>("MatchingValue")
                        .HasColumnType("float");

                    b.Property<int>("ProfilesExternId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("EntityInternEntitiesId");

                    b.HasIndex("EntityMatchStatusId");

                    b.HasIndex("MatchingValue");

                    b.HasIndex("ProfilesExternId");

                    b.ToTable("EntityMatchResults");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.EntityMatchStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<short>("Sort")
                        .HasColumnType("smallint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EntityMatchStatuses");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.EntitySource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EntitySources");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.MatchResultStateChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MatchResultId")
                        .HasColumnType("int");

                    b.Property<int>("NewMatchStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchResultId");

                    b.HasIndex("NewMatchStatusId");

                    b.HasIndex("UpdateDate");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("MatchResultStateChanges");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.ProfileExtern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EntitySourceId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProfileRiskLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("EntitySourceId");

                    b.HasIndex("LastName");

                    b.HasIndex("ProfileRiskLevelId");

                    b.ToTable("ProfilesExtern");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.ProfileRiskLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Sort")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("ProfileRiskLevels");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.EntityInternEntity", b =>
                {
                    b.HasOne("ComponentLibTests.Domain.Entities.EntityInternRiskLevel", "EntityInternRiskLevel")
                        .WithMany("EntityInternEntities")
                        .HasForeignKey("EntityInternRiskLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EntityInternRiskLevel");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.EntityMatchResult", b =>
                {
                    b.HasOne("ComponentLibTests.Domain.Entities.EntityInternEntity", "EntityInternEntity")
                        .WithMany("EntityMatchResults")
                        .HasForeignKey("EntityInternEntitiesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComponentLibTests.Domain.Entities.EntityMatchStatus", "EntityMatchStatus")
                        .WithMany("EntityMatchResults")
                        .HasForeignKey("EntityMatchStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComponentLibTests.Domain.Entities.ProfileExtern", "ProfileExtern")
                        .WithMany("EntityMatchResults")
                        .HasForeignKey("ProfilesExternId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntityInternEntity");

                    b.Navigation("EntityMatchStatus");

                    b.Navigation("ProfileExtern");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.MatchResultStateChange", b =>
                {
                    b.HasOne("ComponentLibTests.Domain.Entities.EntityMatchResult", "EntityMatchResult")
                        .WithMany("MatchResultStateChanges")
                        .HasForeignKey("MatchResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComponentLibTests.Domain.Entities.EntityMatchStatus", "NewMatchStatus")
                        .WithMany("MatchResultStateChanges")
                        .HasForeignKey("NewMatchStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComponentLibTests.Domain.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("MatchResultStateChanges")
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntityMatchResult");

                    b.Navigation("NewMatchStatus");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.ProfileExtern", b =>
                {
                    b.HasOne("ComponentLibTests.Domain.Entities.EntitySource", "EntitySource")
                        .WithMany("ProfilesExtern")
                        .HasForeignKey("EntitySourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComponentLibTests.Domain.Entities.ProfileRiskLevel", "ProfileRiskLevel")
                        .WithMany("ProfilesExtern")
                        .HasForeignKey("ProfileRiskLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EntitySource");

                    b.Navigation("ProfileRiskLevel");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("MatchResultStateChanges");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.EntityInternEntity", b =>
                {
                    b.Navigation("EntityMatchResults");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.EntityInternRiskLevel", b =>
                {
                    b.Navigation("EntityInternEntities");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.EntityMatchResult", b =>
                {
                    b.Navigation("MatchResultStateChanges");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.EntityMatchStatus", b =>
                {
                    b.Navigation("EntityMatchResults");

                    b.Navigation("MatchResultStateChanges");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.EntitySource", b =>
                {
                    b.Navigation("ProfilesExtern");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.ProfileExtern", b =>
                {
                    b.Navigation("EntityMatchResults");
                });

            modelBuilder.Entity("ComponentLibTests.Domain.Entities.ProfileRiskLevel", b =>
                {
                    b.Navigation("ProfilesExtern");
                });
#pragma warning restore 612, 618
        }
    }
}
